package com.negd.viksit.bharat.enums;

public enum PresentStatus {
	NOT_STARTED, YET_TO_BE_INITIATED, INITIATED,
//    UNDER_IMPLEMENTATION,
	ON_TRACK, DELAYED, SUBSTANTIALLY_COMPLETED, FULLY_COMPLETED, ON_HOLD
}
